# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Liberty Bremerhaven
email: sales@liberty-bremerhaven.com

description: > # this means to ignore newlines until "baseurl:"
  THE LIBERTY – Bremerhavens neues Themenhotel, das Anfang 2018 eröffnet wurde, liegt an einzigartiger, historischer Stelle am neuen Hafen wo über 7 Millionen Auswanderer Europa verließen und Ihr Glück in der neuen Welt suchten.
  Das luxuriöse, moderne und elegante Ambiente des 4 Sterne SUPERIOR Hotels, wird  ein weiterer Anziehungspunkt in der Seestadt Bremerhaven sein.

description-eng: > # this means to ignore newlines until "baseurl:"
  The Liberty, which will open in early 2018, is located in a unique, historic spot on the “neuen Hafen” where more than 7 million emigrants left Europe seeking their fortune in the New World. The luxurious, modern and elegant ambience of the 4 star SUPERIOR Hotel will be another attraction in the seaside town of Bremerhaven.

room-de: > # this means to ignore newlines until "baseurl:"
  Das Hotel umfasst 93 elegant ausgestattete Zimmer im 4 Sterne Superior Segment, mit einer Größe von ca. 24 m² bis 30 m², sowie 5 großzügige Juniorsuiten und Suiten mit eigener Terrasse in der 5. Hoteletage. Von den über 60 Water-View-Zimmern mit eigenem Balkonschweift der Blick über den Yachthafen raus auf die Außenweser und Nordsee.

room-eng: > # this means to ignore newlines until "baseurl:"
  The hotel comprises of 93 elegantly crafted rooms in the 4-star superior segment, with a size of approx. 24 m² to 30 m², as well as 5 spacious junior suites and suites with their own terrace on the 5th floor of the hotel. From the more than 60 Water View rooms with their own balcony, the view over the marina out to the outer Weser and North Sea.


mulberry-de: > # this means to ignore newlines until "baseurl:"
  Direkt an der Kaje der Auswanderer verwöhnt das Restaurant ‚Mulberry Street‘ die Gäste mit einem vielfältigen Frühstücksbuffet, sowie raffinierter und feiner Küche im New York-Style.

mulberry-eng: > # this means to ignore newlines until "baseurl:"
  Direct on the emigration quay, the 'Mulberry Street' restaurant pampers guests with an ample breakfast buffet, as well as refined and fine New York-style cuisine.

bar-de: > # this means to ignore newlines until "baseurl:"
  Internationale Drinks und Cocktails im anspruchsvollen Design, können in der ‚New York‘ Bar in der 5. Etage des Hotels oder, bei schönem Wetter, auf der vorgelagerten großen Terrasse genossen werden.

bar-eng: > # this means to ignore newlines until "baseurl:"
  International drinks and signature cocktails can be enjoyed at the New York Bar on the 5th floor of the hotel or, if the weather is nice, on the large terrace outside.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.libertybremerhaven.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - octopress-autoprefixer
  
exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
  sass_dir: assets/stylesheets
  style: :compressed