# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Liberty Bremerhaven
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  THE LIBERTY – Bremerhavens neues Themenhotel, das Anfang 2018 eröffnet wurde, liegt an einzigartiger, historischer Stelle am neuen Hafen wo über 7 Millionen Auswanderer Europa verließen und Ihr Glück in der neuen Welt suchten.
  Das luxuriöse, moderne und elegante Ambiente des 4 Sterne SUPERIOR Hotels, wird  ein weiterer Anziehungspunkt in der Seestadt Bremerhaven sein.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.libertybremerhaven.de/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
sass:
  sass_dir: assets/stylesheets
  style: :compressed